### ISSUE TITLE
Enhance error handling accessibility

### ISSUE THREAD

**Issue by gustavpursche** [guillaumepotier/Parsley.js#640]
First of all - thanks for creating this amazing library. I'm currently doing research on form validation frameworks, since I have to decide which one to use in the near future for a big project.
Therefore I have respect quite strict accessibility rules. I started to add basic aria roles/states here: [e412198](https://github.com/gustavpursche/Parsley.js/commit/12413b8f425b7e4911c195c031126e422febbfcf#diff-2)

**TODO**
- [x] Add ``role="alert"`` attribute to fields with errors
- [x] Add ``aria-invalid`` attribute to fields with errors
- [ ] Add ``aria-labelledby="#ID"`` with reference to elements id, containing the error message. Therefore every error message-item should have it's own id.
- [ ] Extend multiple validation-fields to use fieldsets as wrapper with ``aria-required``, ``aria-invalid`` attributes
- [ ] Create error summary (above submit button) with list of links (containing anchors to the error fields in href) and errormessages (Example: [error summary](http://www.accessible-webapplications.com/wienfluss-form-framework/all.html)). This should have an option to enable/disable in the end.

Does somebody already work on that? Is that something, which you would like to integrate into the project?
Maybe you could also give me some hints, where to add what (mainly the id-stuff for error messages), since I started today to read the code.

Cheers.

**Comment by philgyford** [comment]
Does anyone know if any progress was made on this? I'm using Parsley for a project at the moment but we need it to be a lot more accessible.

**Comment by gustavpursche** [comment]
@philgyford Not yet - since the effort to extend the library was too big for the project, the company decided for another framework. If you like we could work together in out spare time on that - I believe it's an important issue ...

**Comment by philgyford** [comment]
It is. Unfortunately I don't have the time on this project to devote to it (we're in a "quick-n-dirty" stage) so I'll have to leave it. I suspect that in future we'll switch to doing JS validation a different way, so that we sync up our back- and front-end validation a bit better, but also have the ability to add the required accessibility features.

**Comment by marcandre** [comment]
This looks like a great feature to add.
Maybe I can help?

**Comment by juliemoynat** [comment]
Hi,

I've created another ticket because I didn't find this one... It's here: https://github.com/CalderaWP/Caldera-Forms/issues/1500
My ticket was tagged has a major bug and this one should also be tagged "bug:major" and "accessibility" because blind people won't be able to correct their errors now.

Instead of `aria-labelledby` attribute on the field, I prefer `aria-describedby` because `aria-labelledby` will replace the `label` tag. But, if we put both `label` ID and error ID in `aria-labelledby` attribute, it will work.
Example:
`
<input type="text" aria-labelledby="label-id error-id" />
`

I'm also adding 2 points:
1. The error message in the `.help-block` element can change (from required field to syntax error for example) so, it should have an `aria-live="polite"` attribute. Screen readers would read the text as soon as it's changing.
2. The error message should be in a `<p>` tag has a paragraph.

**Comment by Shelob9** [comment]
I am working on creating a script to fix accessibility problems in parsely and will separate it out a package so it can be npm installed. See: https://github.com/CalderaWP/Caldera-Forms/issues/1501

**Comment by marcandre** [comment]
Unless it involves a lot of code, it would be even better if it was integrated in parsley itself.

**Comment by aequasi** [comment]
For what its worth @guillaumepotier 

> Not everyone want to be accessibility standards compliant

Everyone is required to be ADA compliant (in the United States at least).

**Comment by LukaszJaro** [comment]
It's law in Canada as well.

Accessibility laws
Ontario has laws to improve accessibility for people with disabilities. Learn about the standards you need to follow and reporting deadlines for complying with accessibility requirements.
